#-----------**LAB-7**-------------
#-------**Ensemble Methods**-----

In [ ]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.pipeline import Pipeline

In [ ]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier

In [ ]:
from sklearn.ensemble import BaggingClassifier
from sklearn.ensemble import AdaBoostClassifier
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.ensemble import StackingClassifier

In [ ]:
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    classification_report,
    confusion_matrix
)

In [ ]:
df = pd.read_csv("Iris.csv")

In [ ]:
df = df.drop("Id", axis=1)

In [ ]:
le = LabelEncoder()
X = df.drop('Species', axis=1)
y = df['Species']
y = le.fit_transform(y)

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

In [ ]:
scaler = StandardScaler()

In [ ]:
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [ ]:
# Bagging Classifier
bagging_model = BaggingClassifier(
    estimator=DecisionTreeClassifier(),
    n_estimators=100,
    random_state=42
)

In [ ]:
bagging_model.fit(X_train, y_train)

BaggingClassifier(estimator=DecisionTreeClassifier(), n_estimators=100,
                  random_state=42)

In [ ]:
y_pred_bag = bagging_model.predict(X_test)

In [ ]:
accuracy = accuracy_score(y_test, y_pred_bag)
precision = precision_score(y_test, y_pred_bag, average='weighted')
recall = recall_score(y_test, y_pred_bag, average='weighted')
f1 = f1_score(y_test, y_pred_bag, average='weighted')

In [ ]:
print("Bagging Classifier Results")
print("Accuracy:", accuracy)
print("Precision:", precision)
print("Recall:", recall)
print("F1 Score:", f1)

Bagging Classifier Results
Accuracy: 0.9333333333333333
Precision: 0.9333333333333333
Recall: 0.9333333333333333
F1 Score: 0.9333333333333333


In [ ]:
print("\nClassification Report:")
print(classification_report(y_test, y_pred_bag))


Classification Report:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       0.90      0.90      0.90        10
           2       0.90      0.90      0.90        10

    accuracy                           0.93        30
   macro avg       0.93      0.93      0.93        30
weighted avg       0.93      0.93      0.93        30



In [ ]:
print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred_bag))


Confusion Matrix:
[[10  0  0]
 [ 0  9  1]
 [ 0  1  9]]


In [ ]:
# Boosting Classifiers
# AdaBoost Algorithm with Decision Tree as base estimator
adaboost_model = AdaBoostClassifier(
    estimator=DecisionTreeClassifier(max_depth=1),
    n_estimators=100,
    learning_rate=0.5,
    random_state=42
)

adaboost_model.fit(X_train, y_train)
y_pred_adaboost = adaboost_model.predict(X_test)

# Gradient Boosting Classifier with default parameters
gboost_model = GradientBoostingClassifier(
    n_estimators=100,
    learning_rate=0.1,
    random_state=42
)

In [ ]:
accuracy1 = accuracy_score(y_test, y_pred_adaboost)
precision1 = precision_score(y_test, y_pred_adaboost, average='weighted')
recall1 = recall_score(y_test, y_pred_adaboost, average='weighted')
f1_1 = f1_score(y_test, y_pred_adaboost, average='weighted')

In [ ]:
print("Boosting Classifier Results")
print("Accuracy:", accuracy1)
print("Precision:", precision1)
print("Recall:", recall1)
print("F1 Score:", f1_1)

Boosting Classifier Results
Accuracy: 0.9666666666666667
Precision: 0.9696969696969696
Recall: 0.9666666666666667
F1 Score: 0.9665831244778613


In [ ]:
print("\nClassification Report:")
print(classification_report(y_test, y_pred_adaboost))


Classification Report:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       1.00      0.90      0.95        10
           2       0.91      1.00      0.95        10

    accuracy                           0.97        30
   macro avg       0.97      0.97      0.97        30
weighted avg       0.97      0.97      0.97        30



In [ ]:
print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred_adaboost))


Confusion Matrix:
[[10  0  0]
 [ 0  9  1]
 [ 0  0 10]]


In [ ]:
# Stacking Classifier
base_learners = [
    ('dt', DecisionTreeClassifier()),
    ('knn', KNeighborsClassifier()),
    ('lr', LogisticRegression(max_iter=1000))
]

stacking_model = StackingClassifier(
    estimators=base_learners,
    final_estimator=LogisticRegression(),
    cv=5
)

In [ ]:
stacking_model.fit(X_train, y_train)
y_pred_stack = stacking_model.predict(X_test)

In [ ]:
accuracy2 = accuracy_score(y_test, y_pred_stack)
precision2 = precision_score(y_test, y_pred_stack, average='weighted')
recall2 = recall_score(y_test, y_pred_stack, average='weighted')
f1_2 = f1_score(y_test, y_pred_stack, average='weighted')

In [ ]:
print("Stacking Classifier Results")
print("Accuracy:", accuracy1)
print("Precision:", precision1)
print("Recall:", recall1)
print("F1 Score:", f1_1)

Stacking Classifier Results
Accuracy: 0.9666666666666667
Precision: 0.9696969696969696
Recall: 0.9666666666666667
F1 Score: 0.9665831244778613


In [ ]:
print("\nClassification Report:")
print(classification_report(y_test, y_pred_stack))


Classification Report:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       0.91      1.00      0.95        10
           2       1.00      0.90      0.95        10

    accuracy                           0.97        30
   macro avg       0.97      0.97      0.97        30
weighted avg       0.97      0.97      0.97        30



In [ ]:
print("\nConfusion Matrix: ")
print(confusion_matrix(y_test, y_pred_stack))


Confusion Matrix: 
[[10  0  0]
 [ 0 10  0]
 [ 0  1  9]]


# Breast Cancer Dataset

In [ ]:
pip install ucimlrepo

In [ ]:
from ucimlrepo import fetch_ucirepo

# fetch dataset
breast_cancer = fetch_ucirepo(id=14)

# data (as pandas dataframes)
X = breast_cancer.data.features
y = breast_cancer.data.targets

# metadata
print(breast_cancer.metadata)

# variable information
print(breast_cancer.variables)

{'uci_id': 14, 'name': 'Breast Cancer', 'repository_url': 'https://archive.ics.uci.edu/dataset/14/breast+cancer', 'data_url': 'https://archive.ics.uci.edu/static/public/14/data.csv', 'abstract': 'This breast cancer domain was obtained from the University Medical Centre, Institute of Oncology, Ljubljana, Yugoslavia. This is one of three domains provided by the Oncology Institute that has repeatedly appeared in the machine learning literature. (See also lymphography and primary-tumor.)', 'area': 'Health and Medicine', 'tasks': ['Classification'], 'characteristics': ['Multivariate'], 'num_instances': 286, 'num_features': 9, 'feature_types': ['Categorical'], 'demographics': ['Age'], 'target_col': ['Class'], 'index_col': None, 'has_missing_values': 'yes', 'missing_values_symbol': 'NaN', 'year_of_dataset_creation': 1988, 'last_updated': 'Thu Mar 07 2024', 'dataset_doi': '10.24432/C51P4M', 'creators': ['Matjaz Zwitter', 'Milan Soklic'], 'intro_paper': None, 'additional_info': {'summary': 'Thi

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
df = pd.read_csv("https://archive.ics.uci.edu/static/public/14/data.csv")

print(df.head())

     age menopause tumor-size inv-nodes node-caps  deg-malig breast  \
0  30-39   premeno      30-34       0-2        no          3   left   
1  40-49   premeno      20-24       0-2        no          2  right   
2  40-49   premeno      20-24       0-2        no          2   left   
3  60-69      ge40      15-19       0-2        no          2  right   
4  40-49   premeno        0-4       0-2        no          2  right   

  breast-quad irradiat                 Class  
0    left_low       no  no-recurrence-events  
1    right_up       no  no-recurrence-events  
2    left_low       no  no-recurrence-events  
3     left_up       no  no-recurrence-events  
4   right_low       no  no-recurrence-events  


In [ ]:
df = df.replace('?', np.nan)

# Fill missing with mode (best for categorical)
for col in df.columns:
    df[col] = df[col].fillna(df[col].mode()[0])

In [ ]:
from sklearn.preprocessing import LabelEncoder

In [ ]:
le_target = LabelEncoder()
df['Class'] = le_target.fit_transform(df['Class'])

In [ ]:
X = df.drop('Class', axis=1)
y = df['Class']

X = pd.get_dummies(X)

In [ ]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

In [ ]:
scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [ ]:
bagging_model = BaggingClassifier(
    estimator=DecisionTreeClassifier(),
    n_estimators=100,
    random_state=42
)

bagging_model.fit(X_train, y_train)
y_pred_bag = bagging_model.predict(X_test)

In [ ]:
adaboost_model = AdaBoostClassifier(
    estimator=DecisionTreeClassifier(max_depth=1),
    n_estimators=100,
    learning_rate=0.5,
    random_state=42
)

adaboost_model.fit(X_train, y_train)
y_pred_adaboost = adaboost_model.predict(X_test)

In [ ]:
gboost_model = GradientBoostingClassifier(
    n_estimators=100,
    learning_rate=0.1,
    random_state=42
)

gboost_model.fit(X_train, y_train)
y_pred_gboost = gboost_model.predict(X_test)

In [ ]:
base_learners = [
    ('dt', DecisionTreeClassifier()),
    ('knn', KNeighborsClassifier()),
    ('lr', LogisticRegression(max_iter=1000))
]

stacking_model = StackingClassifier(
    estimators=base_learners,
    final_estimator=LogisticRegression(),
    cv=5
)

stacking_model.fit(X_train, y_train)
y_pred_stack = stacking_model.predict(X_test)

In [ ]:
def evaluate(y_test, y_pred, name):
    print(f"\n{name} Results")
    print("Accuracy:", accuracy_score(y_test, y_pred))
    print("Precision:", precision_score(y_test, y_pred, average='weighted'))
    print("Recall:", recall_score(y_test, y_pred, average='weighted'))
    print("F1 Score:", f1_score(y_test, y_pred, average='weighted'))

    print("\nClassification Report:")
    print(classification_report(y_test, y_pred))

    print("\nConfusion Matrix:")
    print(confusion_matrix(y_test, y_pred))

In [ ]:
evaluate(y_test, y_pred_bag, "Bagging")
evaluate(y_test, y_pred_adaboost, "AdaBoost")
evaluate(y_test, y_pred_gboost, "Gradient Boosting")
evaluate(y_test, y_pred_stack, "Stacking")


Bagging Results
Accuracy: 0.6896551724137931
Precision: 0.6792836140069499
Recall: 0.6896551724137931
F1 Score: 0.6836514778325123

Classification Report:
              precision    recall  f1-score   support

           0       0.77      0.80      0.79        41
           1       0.47      0.41      0.44        17

    accuracy                           0.69        58
   macro avg       0.62      0.61      0.61        58
weighted avg       0.68      0.69      0.68        58


Confusion Matrix:
[[33  8]
 [10  7]]

AdaBoost Results
Accuracy: 0.7586206896551724
Precision: 0.743013406256253
Recall: 0.7586206896551724
F1 Score: 0.740987460815047

Classification Report:
              precision    recall  f1-score   support

           0       0.79      0.90      0.84        41
           1       0.64      0.41      0.50        17

    accuracy                           0.76        58
   macro avg       0.71      0.66      0.67        58
weighted avg       0.74      0.76      0.74        5

In [ ]:
results = pd.DataFrame({
    'Model': ['Bagging', 'AdaBoost', 'Gradient Boosting', 'Stacking'],
    'Accuracy': [
        accuracy_score(y_test, y_pred_bag),
        accuracy_score(y_test, y_pred_adaboost),
        accuracy_score(y_test, y_pred_gboost),
        accuracy_score(y_test, y_pred_stack)
    ],
    'Precision': [
        precision_score(y_test, y_pred_bag, average='weighted'),
        precision_score(y_test, y_pred_adaboost, average='weighted'),
        precision_score(y_test, y_pred_gboost, average='weighted'),
        precision_score(y_test, y_pred_stack, average='weighted')
    ],
    'Recall': [
        recall_score(y_test, y_pred_bag, average='weighted'),
        recall_score(y_test, y_pred_adaboost, average='weighted'),
        recall_score(y_test, y_pred_gboost, average='weighted'),
        recall_score(y_test, y_pred_stack, average='weighted')
    ],
    'F1 Score': [
        f1_score(y_test, y_pred_bag, average='weighted'),
        f1_score(y_test, y_pred_adaboost, average='weighted'),
        f1_score(y_test, y_pred_gboost, average='weighted'),
        f1_score(y_test, y_pred_stack, average='weighted')
    ]
})

results = results.sort_values(by='F1 Score', ascending=False)

print(results)

               Model  Accuracy  Precision    Recall  F1 Score
1           AdaBoost  0.758621   0.743013  0.758621  0.740987
0            Bagging  0.689655   0.679284  0.689655  0.683651
2  Gradient Boosting  0.672414   0.655788  0.672414  0.662344
3           Stacking  0.672414   0.618879  0.672414  0.629648
